#!/usr/bin/env bash
# Script that install nginx

if ! [ -x "$(command -v nginx)" ]; then
    apt update -y;
    apt install nginx -y;
fi

service nginx start;
sed -i '/80/8080/' /etc/nginx/sites-enabled/default;
echo "Holberton School" > /var/www/html/index.nginx-debian.html;
nginx -s reload;
